
        /*
         * DO NOT EDIT THIS FILE
         * This file is automatically generated at build time.
         */
        package com.funambol.android;
        public class BuildInfo
        {
            public final static String VERSION = "10.0.4 (debug)";
            public final static String DATE = "20140226";
            public final static String MODE = "debug";
            public final static String PACKAGE_NAME = "com.funambol.androidsync";
            public final static boolean UNIT_TEST = false;
            public final static boolean TEST_RECORDING_ENABLED = false;

            public final static boolean isInDebugMode()
            { return "debug".equalsIgnoreCase(MODE); }
        }
        